/**
 * Part 1 of the Japanese 14-part message of 7 December 1941 — the note breaking
 * off negotiations with the United States, delivered in Washington after the
 * attack on Pearl Harbor had already begun.
 *
 * Ciphertext and plaintext are aligned character for character. '-' marks a
 * garble in the intercept as received; those positions are skipped when
 * comparing, but the machine still steps over them.
 *
 * Key: switches `9-1,24,6-23`, alphabet `NOKTYUXEQLHBRMPDICJASVWGZF`.
 *
 * Source: Freeman, Sullivan & Weierud, "PURPLE Revealed", Cryptologia 27(1),
 * 2003; transcription via the MIT-licensed reference implementation at
 * https://github.com/gremmie/purple
 */

export const PART1_KEY = "9-1,24,6-23";
export const PART1_ALPHABET = "NOKTYUXEQLHBRMPDICJASVWGZF";

export const PART1_CIPHERTEXT =
	"ZTXODNWKCCMAVNZXYWEETUQTCIMNVEUVIWBLUAXRRTLVARGNTPCNOIUPJLCIVRTP" +
	"JKAUHVMUDTHKTXYZELQTVWGBUHFAWSHULBFBHEXMYHFLOWD-KWHKKNXEBVPYHHGH" +
	"EKXIOHQHUHWIKYJYHPPFEALNNAKIBOOZNFRLQCFLJTTSSDDOIOCVT-ZCKQTSHXTI" +
	"JCNWXOKUFNQR-TAOIHWTATWVHOTGCGAKVANKZANMUINYOYJFSRDKKSEQBWKIOORJ" +
	"AUWKXQGUWPDUDZNDRMDHVHYPNIZXBGICXRMAWMFTIUDBXIENLONOQVQKYCOTVSHV" +
	"NZZQPDLMXVNRUUNQFTCDFECZDFGMXEHHWYONHYNJDOVJUNCSUVKKEIWOLKRBUUSO" +
	"ZUIGNISMWUOSBOBLJXERZJEQYQMTFTXBJNCMJKVRKOTSOPBOYMKIRETINCPSQJAW" +
	"VHUFKRMAMXNZUIFNOPUEMHGLOEJHZOOKHHEEDNIHXFXFXGPDZBSKAZABYEKYEPNI" +
	"YSHVKFRFPVCJTPTOYCNEIQBFEXMERMIZLGDRXZORLZFSQYPZFATZCHUGRNHWDDTA" +
	"IHYOOCOODUZYIWJROOJUMUIHRBEJFONAXGNCKAOARDIHCDZKIXPR--DIMUWOMHLT" +
	"JSOUXPFKGEPWJOMTUVKMWRKTACUPIGAFEDFVRKXFXLFGURDETJIYOLKBHZKXOJDD" +
	"OVRHMMUQBFOWRODMRMUWNAYKYPISDLHECKINLJORKWNWXADAJOLONOEVMUQDFIDS" +
	"PEBBPWROFBOPAZJEUUSBHGIORCSUUQKIIEHPCTJRWSOGLETZLOUKKEOJOSMKJBWU" +
	"CDDCPYUUWCSSKWWVLIUPKYXGKQOKAZTEZFHGVPJFEWEUBKLIZLWKKOBXLEPQPDAT" +
	"WUSUUPKYRHNWDZXXGTWDDNSHDCBCJXAOOEEPUBPWFRBQSFXSEZJJYAANMG-WLYMG" +
	"WAQDGIVNOHKOUTIXYFOKNGGBFGANPWTUYLBEFFKUFLEXOIUUANVMMJEQUSFHFDOH" +
	"QLAKWTBYYYLNTLYTSXCGKCEEWQRYAVGRKXIANPXNOFVXGKJFAVKLTHOCXCIVKOLX" +
	"TJTUNCLQCICRUIIWQDDMOTPRVTJKKSKFHXFKMDIKIZWROGZJYMTMNOVMFJ-OKTEI" +
	"VMYANOHNNYPDLEXCFRRNEBLMNYEBGNHCZZCFNWGGRHRIUUTTILKLODUYZKQOZMMN" +
	"HASXHLPVTNGHQDAJIUGOOSZ-----ZRTGWFBLKI--------YBDABJ-----WYOEANV" +
	"---OM";

export const PART1_PLAINTEXT =
	"FOVTATAKIDASINIMUIMINOMOXIWOIRUBESIFYXXFCKZZRDXOOVBTNFYXFAEMEMOR" +
	"ANDUMFIOFOVOOMOJIBAKARIFYXRAICCYLFCBBCFCTHEGOVE-NMENTOFJAPANLFLP" +
	"ROMPTEDBYAGENUINEDESIRETOCOMETOANAMICABLEUNDERSTANDIN-WITHTHEGOV" +
	"ERNMENTOFTHE-NITEDSTATESINORDERTHATTHETWOCOUNTRIESBYTHEIRJOINTEF" +
	"FORTSMAYSECURETHEPEACEOFTHEPACIFICAREAANDTHEREBYCONTRIBUTETOWARD" +
	"THEREALIZATIONOFWORLDPEACELFLHASCONTINUEDNEGOTIATIONSWITHTHEUTMO" +
	"STSINCERITYSINCEAPRILLASTWITHTHEGOVERNMENTOFTHEUNITEDSTATESREGAR" +
	"DINGTHEADJUSTMENTANDADVANCEMENTOFJAPANESEVVFAMERICANRELATIONSAND" +
	"THESTABILIZATIONOFTHEPACIFICAREACFCCCFTHEJAPANESEQOVERNMENXHASTH" +
	"EHONORTOSTATEFRANKLYITSVIEWSCONCERNINGTHECLAIMSTHEAM--VCANGOVERN" +
	"MENTHASUERSISTENTLYMAINTAINEDASWELLASTHEMEASURESTHEUNITEDSTATESA" +
	"NDGREATBRITAINHAVETAKENTOWARDJAPANDURINGTHKSEEIGHTMONTHSCYCCCFLF" +
	"CDDCFCITISTHEIMMUTABLXPOLWCYOFTHEJAPANESEGOVERNMENTTOINSURETHEST" +
	"ABILITYOFEASTASIAANDTOPROMOTEWORLZPEACELFLANDTHEREBYTOEIABLEALLN" +
	"ATIONSTOFINDEACHITSPROPERPLACEINTHEWORLDCFCCCFEVERSINCETHE-HINAA" +
	"FFAIRBROKEOUTOWINGTOTHEFAILUREONTHEPARTOFCHINATOCOMPREHENLJAPANV" +
	"CFSTRUEYNTENTIONSLFLTWEJAPANESEGOVERNMENTHASSTRIVENFORTHERESTORA" +
	"TIONOFPEACEANDIMHASCONSISTENTLYEXERTEDITSBESTEFFORTSTOPREV-NTTHE" +
	"EXTENTIONOFWARVVFLIKEVISTURBANCESCFCNSIASALSOTOTHATENDTNATINSEPT" +
	"EMBERLASTYEARJAPANCONCL-----HETRIPAITI--------THGERM-----DYTALYC" +
	"---OV";
